export const waitingCSS = `
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:100px}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 system-ui,-apple-system,sans-serif;overflow-wrap:anywhere}
html{--bg:#f4f8fb;--paper:#fff;--ink:#183345;--muted:#536e80;--accent:#247b9f;--soft:#e4f0f7;--hero:linear-gradient(135deg,#edf7fc,#cde7f1);--radius:20px;--heading:inherit;--heroink:var(--ink);--heromuted:var(--muted);--columns:1fr;--align:center;--justify:center}
html[data-theme=forest]{--bg:#f7f6ee;--ink:#253f32;--muted:#647364;--accent:#305b46;--soft:#e9eddf;--hero:#eef0e4;--radius:5px;--heading:Georgia,serif;--columns:1.3fr .7fr;--align:left;--justify:flex-start}
html[data-theme=midnight]{--bg:#edf1f6;--ink:#182a43;--muted:#576a82;--accent:#315c92;--soft:#dfe7f1;--hero:linear-gradient(135deg,#142237,#243d60);--heroink:#fff;--heromuted:#c1cee1;--radius:7px;--columns:1.2fr .8fr;--align:left;--justify:flex-start}
html[data-theme=sand]{--bg:#fbf5ed;--ink:#482e23;--muted:#786153;--accent:#895136;--soft:#eee2d1;--hero:linear-gradient(120deg,#f4e6d3,#fcf8f1);--radius:12px;--heading:Georgia,serif;--columns:1.2fr .8fr;--align:left;--justify:flex-start}
html[data-theme=violet]{--bg:#f8f6fc;--ink:#312648;--muted:#706180;--accent:#6753ad;--soft:#ece5f5;--hero:radial-gradient(ellipse at 10% 0%,#e5dafb,transparent 60%),linear-gradient(135deg,#f8f4ff,#e8e1f6);--radius:30px}
a{color:inherit;text-decoration:none}a:focus-visible{outline:3px solid var(--accent);outline-offset:5px}.wrap{max-width:1120px;padding:0 28px;margin:auto}.top{background:var(--bg);border-bottom:1px solid var(--soft)}.top .wrap{min-height:86px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;gap:12px;align-items:center}.mark{width:44px;height:44px;background:var(--accent);color:white;border-radius:var(--radius);display:grid;place-items:center;font-weight:800;flex-shrink:0}.brand strong{display:block;font-size:14px}.brand small{display:block;font-size:11px;color:var(--muted)}nav{display:flex;gap:24px;font-size:12px;flex-shrink:0}
.hero{background:var(--hero);padding:76px 0 64px;border-radius:0 0 36px 36px}.hero-grid{display:grid;grid-template-columns:var(--columns);gap:38px;align-items:center;text-align:var(--align)}.eyebrow{display:inline-flex;align-items:center;gap:8px;font-size:10px;letter-spacing:2px;text-transform:uppercase;font-weight:700}.eyebrow:before{content:'';width:6px;height:6px;background:currentColor;border-radius:50%}.hero .eyebrow{color:var(--heromuted)}h1,h2,h3{font-family:var(--heading);line-height:1.18;margin:0}h1{font-size:clamp(32px,5vw,56px);letter-spacing:-1.5px;color:var(--heroink);margin-top:18px}.hero p{max-width:640px;margin:22px auto 0;color:var(--heromuted);font-size:15px;white-space:pre-line}.actions{display:flex;gap:12px;justify-content:var(--justify);flex-wrap:wrap;margin-top:28px}.button{display:inline-flex;align-items:center;justify-content:center;padding:13px 22px;background:var(--accent);color:#fff;border-radius:var(--radius);font-size:12px;font-weight:700}.button.light{background:var(--paper);color:var(--ink);border:1px solid var(--soft)}
.hero-facts{display:flex;flex-wrap:wrap;gap:12px;justify-content:var(--justify)}.fact{background:var(--paper);border:1px solid var(--soft);padding:18px 22px;border-radius:var(--radius);text-align:left;flex:1;min-width:150px}.fact small{display:block;font-size:9px;text-transform:uppercase;letter-spacing:1px;color:var(--accent);font-weight:750}.fact strong{display:block;font-size:13px;margin-top:7px;color:var(--ink)}.section{padding:62px 0 30px}.section-title{text-align:var(--align);margin-bottom:28px}.section-title .eyebrow{color:var(--accent)}h2{font-size:30px;margin-top:12px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:var(--paper);border:1px solid var(--soft);border-radius:var(--radius);padding:30px 26px;box-shadow:0 8px 28px #192b4010;scroll-margin-top:24px}.card .number{font-size:12px;letter-spacing:2px;color:var(--accent)}h3{font-size:18px;margin:17px 0 15px}.card p,.card li{color:var(--muted);font-size:13px;white-space:pre-line}.card p{margin:0}.card ul{padding-left:18px;margin:0}.card li{margin:9px 0}.contact{display:grid;gap:14px}.contact a{font-size:13px;color:var(--accent);font-weight:650}
.details{background:var(--soft);padding:42px 0 50px;margin-top:30px}.details h2{font-size:25px}.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;margin-top:25px}footer{background:var(--ink);color:white;padding:32px 0}footer .wrap{display:flex;justify-content:space-between;gap:20px;align-items:center}footer strong{font-size:13px}footer small{display:block;font-size:11px;opacity:.75;margin-top:7px}footer a{font-size:12px}
@media(max-width:760px){.wrap{padding:0 20px}.top .wrap{align-items:flex-start;padding-top:20px;padding-bottom:20px;flex-direction:column;gap:18px}nav{gap:22px;flex-wrap:wrap}.hero{padding:45px 0}.hero-grid{grid-template-columns:1fr}.cards{grid-template-columns:1fr}.hero-facts{gap:10px}.fact{padding:16px}.section{padding-top:40px}h2{font-size:26px}footer .wrap{align-items:flex-start;flex-direction:column}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
`;
